# Generated by Django 5.1.5 on 2026-05-10 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evenement',
            options={'verbose_name': 'Événement', 'verbose_name_plural': 'Événements'},
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='eventId',
        ),
        migrations.AlterModelTable(
            name='evenement',
            table='evenements',
        ),
        migrations.AddField(
            model_name='inscription',
            name='eventId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='eventApp.evenement'),
        ),
    ]
